# Generated by Django 3.2.4 on 2021-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210628_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due',
            new_name='due_date',
        ),
    ]
